# Generated by Django 5.2.3 on 2025-06-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_name', models.TextField(max_length=100, null=True)),
                ('userpassword', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('useremail', models.CharField(max_length=100)),
                ('usernumber', models.CharField(max_length=12, null=True)),
                ('userbirthdate', models.DateField(null=True)),
                ('usergender', models.TextField(max_length=20, null=True)),
            ],
        ),
    ]
