# Generated by Django 5.2.3 on 2025-06-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('adminname', models.TextField(max_length=100)),
                ('adminpassword', models.TextField(max_length=100)),
                ('adminusername', models.TextField(max_length=100)),
                ('adminemail', models.CharField(max_length=100, null=True)),
                ('adminnumber', models.CharField(max_length=12)),
                ('adminbirthdate', models.DateField()),
                ('admingender', models.TextField(max_length=20, null=True)),
                ('adminrole', models.TextField(max_length=2)),
            ],
        ),
    ]
