# Generated by Django 5.2.3 on 2025-06-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventProject', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=100)),
                ('eventdescription', models.TextField()),
                ('eventdate', models.DateField()),
                ('eventtime', models.TimeField()),
                ('eventlocation', models.CharField(max_length=255)),
                ('eventorganizer', models.CharField(max_length=100, null=True)),
                ('max_attendees', models.PositiveIntegerField(null=True)),
                ('contact_number', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
