# Generated by Django 5.2.3 on 2025-06-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventProject', '0004_event_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_image',
            new_name='event_images',
        ),
    ]
