# Generated by Django 5.2.3 on 2025-06-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventProject', '0005_rename_event_image_event_event_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_images',
            new_name='event_image',
        ),
    ]
