# Generated by Django 5.2.3 on 2025-06-10 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventProject', '0006_rename_event_images_event_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('rsvp_status', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], default='YES', max_length=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='EventProject.event')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='EventProject.user')),
            ],
            options={
                'ordering': ['-registration_date'],
                'unique_together': {('eventid', 'userid')},
            },
        ),
    ]
