# Generated by Django 5.2.3 on 2025-06-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventProject', '0009_event_status_event_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
