# Generated by Django 5.2.3 on 2025-06-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventProject', '0010_event_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='feedback',
            field=models.TextField(blank=True, help_text='User feedback about the event', null=True),
        ),
    ]
